// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_approval_voting
List rcpp_approval_voting(List voters, CharacterVector candidates, NumericVector weights);
RcppExport SEXP _mlr3fselect_rcpp_approval_voting(SEXP votersSEXP, SEXP candidatesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type voters(votersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_approval_voting(voters, candidates, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlr3fselect_rcpp_approval_voting", (DL_FUNC) &_mlr3fselect_rcpp_approval_voting, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlr3fselect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
