// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AV_rcpp
List AV_rcpp(List voters, CharacterVector candidates, NumericVector weights);
RcppExport SEXP _mlr3fselect_AV_rcpp(SEXP votersSEXP, SEXP candidatesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type voters(votersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(AV_rcpp(voters, candidates, weights));
    return rcpp_result_gen;
END_RCPP
}
// SAV_rcpp
List SAV_rcpp(List voters, CharacterVector candidates, NumericVector weights);
RcppExport SEXP _mlr3fselect_SAV_rcpp(SEXP votersSEXP, SEXP candidatesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type voters(votersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(SAV_rcpp(voters, candidates, weights));
    return rcpp_result_gen;
END_RCPP
}
// seq_PAV_rcpp
List seq_PAV_rcpp(List voters, CharacterVector candidates, NumericVector weights, int committee_size);
RcppExport SEXP _mlr3fselect_seq_PAV_rcpp(SEXP votersSEXP, SEXP candidatesSEXP, SEXP weightsSEXP, SEXP committee_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type voters(votersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< int >::type committee_size(committee_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_PAV_rcpp(voters, candidates, weights, committee_size));
    return rcpp_result_gen;
END_RCPP
}
// revseq_PAV_rcpp
List revseq_PAV_rcpp(List voters, CharacterVector candidates, NumericVector weights);
RcppExport SEXP _mlr3fselect_revseq_PAV_rcpp(SEXP votersSEXP, SEXP candidatesSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type voters(votersSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type candidates(candidatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(revseq_PAV_rcpp(voters, candidates, weights));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlr3fselect_AV_rcpp", (DL_FUNC) &_mlr3fselect_AV_rcpp, 3},
    {"_mlr3fselect_SAV_rcpp", (DL_FUNC) &_mlr3fselect_SAV_rcpp, 3},
    {"_mlr3fselect_seq_PAV_rcpp", (DL_FUNC) &_mlr3fselect_seq_PAV_rcpp, 4},
    {"_mlr3fselect_revseq_PAV_rcpp", (DL_FUNC) &_mlr3fselect_revseq_PAV_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlr3fselect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
