#' @title FeatureSelectionGenetic
#'
#' @description
#' FeatureSelection child class to conduct genetic search. The comma strategy `(mu, lambda)` selects a new population of size `mu` out of the `lambda > mu` offspring. The plus strategy `(mu + lambda)` uses the joint pool of `mu` parents and `lambda` offspring for selecting `mu` new candidates. Out of those `mu` features, the new `lambda` features are generated by randomly choosing pairs of parents. These are crossed over and `crossover_rate` represents the probability of choosing a feature from the first parent instead of the second parent. The resulting offspring is mutated, i.e., its bits are flipped with probability `mutation_rate`. If `max_features` is set, offspring are repeatedly generated until the setting is satisfied.
#'
#' @section Usage:
#'  ```
#' fs = FeatureSelectionGenetic$new()
#' ```
#' See [FeatureSelection] for a description of the interface.
#'
#' @section Arguments:
#' * `pe` (`[PerformanceEvaluator]`).
#' * `tm` (`[Terminator]`).
#' * `mu` (`integer(1)`
#'   Size of the parent population.
#' * `lambda` (`integer(1)`)
#'   Size of the children population.
#' * `crossover_rate` (`numeric(1)`)
#'   Probability of choosing a bit from the first parent within the crossover mutation.
#' * `mutation_rate` (`numeric(1)`)
#'   Probability of flipping a feature bit, i.e. switch between selecting / deselecting a feature.
#' * `max_features` (`integer(1)`)
#'   Maximum number of features.
#' * `strategy` (`character(1)`)
#'   `plus` or `comma`. Indicates whether to use a (mu, lambda) or (mu + lambda) genetic algorithm.
#'
#' @section Details:
#' `$new()` creates a new object of class [FeatureSelectionGenetic].
#' `$get_result()` Returns best feature combination with performance.
#' `$get_path()` Returns each generation (`mu` feature sets and performanes) as a list entry.
#' The interface is described in [FeatureSelection].
#'
#' @name FeatureSelectionGenetic
#' @family FeatureSelection
#' @examples
#' task = mlr3::mlr_tasks$get("pima")
#' measures = mlr3::mlr_measures$mget(c("classif.acc"))
#' task$measures = measures
#' learner = mlr3::mlr_learners$get("classif.rpart")
#' resampling = mlr3::mlr_resamplings$get("cv", param_vals = list(folds = 5L))
#' pe = PerformanceEvaluator$new(task = task, learner = learner, resampling = resampling)
#' tm = TerminatorRuntime$new(max_time = 20, units = "secs")
#' fs = FeatureSelectionGenetic$new(pe = pe, tm = tm, mu = 10, lambda = 20, strategy = "plus")
#' fs$calculate()
#' fs$get_result()
#' fs$get_path()
NULL

#' @export
#' @include FeatureSelection.R

FeatureSelectionGenetic = R6Class("FeatureSelectionGenetic",
  inherit = FeatureSelection,
  public = list(
    initialize = function(pe, tm, mu, lambda, crossover_rate = 0.5,
      mutation_rate = 0.05, max_features = NA, strategy = "plus") {
      super$initialize(id = "genetic_selection", pe = pe, tm = tm,
        settings = list(
          max_features = checkmate::assert_numeric(max_features, lower = 1, upper = length(pe$task$feature_names)),
          mu = checkmate::assert_numeric(mu),
          lambda = checkmate::assert_numeric(lambda),
          crossover_rate = checkmate::assert_numeric(crossover_rate, lower = 0, upper = 1),
          mutation_rate = checkmate::assert_numeric(mutation_rate, lower = 0, upper = 1),
          strategy = checkmate::assert_string(strategy, pattern = "(^comma$|^plus$)")))

      if (strategy == "comma" & lambda < mu) {
        stop("For comma strategy lambda >= mu")
      }

      self$state = private$initialize_states()
    },

    get_result = function() {
      if (length(self$pe$bmr) > 1) {
        bmr = lapply(self$pe$bmr[1:length(self$pe$bmr)], function(bmr) self$pe$bmr[[1]]$combine(bmr))
      } else {
        bmr = self$pe$bmr
      }
      bmr_best = bmr[[length(bmr)]]$get_best(self$pe$task$measures[[1L]]$id)
      list(
        features = bmr_best$task$feature_names,
        performance = bmr_best$aggregated)
    },
    get_path = function() {
      lapply(self$pe$bmr, function(bmr) {
        aggr = bmr$aggregated()
        aggr = setorderv(aggr, self$pe$task$measures[[1]]$id, order = -1)[1:self$settings$mu, ]
        performance = aggr[, self$pe$task$measures[[1]]$id, with = FALSE][[1]]
        features = lapply(aggr$task, function(task) task$feature_names)
        list(
          features = features,
          performance = performance)
      })
    }
  ),
  private = list(
    calculate_step = function() {

      # Generate population depending on strategy
      if (self$settings$strategy == "plus") {
        states = c(self$state, private$generate_states())
      } else if (self$settings$strategy == "comma") {
        states = private$generate_states()
      }
      named_states = lapply(states, private$binary_to_features)

      # Evaluation
      private$eval_states_terminator(named_states)
      bmr = self$pe$bmr[[length(self$pe$bmr)]]

      # Select mu best results
      aggr = bmr$aggregated()
      aggr = setorderv(aggr, self$pe$task$measures[[1]]$id, order = -1)[1:self$settings$mu, ]

      # Convert feature names to 0/1 encoding and set state
      features = lapply(aggr$task, function(task) {
        task$feature_names
      })
      self$state = lapply(features, function(y) {
        as.numeric(Reduce("|", lapply(y, function(x) x == self$pe$task$feature_names)))
      })
    },
    initialize_states = function() {
      lapply(seq_len(self$settings$mu), function(i) {
        if (is.na(self$settings$max_features)) {
          return(rbinom(length(self$pe$task$feature_names), 1, 0.5))
        }
        x = Inf
        while (sum(x) >= self$settings$max_features) {
          x = rbinom(length(self$pe$task$feature_names), 1, 0.5)
        }
        return(x)
      })
    },
    generate_states = function() {
      lapply(seq_len(self$settings$lambda), function(i) {
        while (TRUE) {
          # Randomly select parents
          parents = sample(1:length(self$state), 2, replace = TRUE)

          # Crossover
          cross = rbinom(length(self$state[[parents[1]]]), 1, self$settings$crossover_rate)
          children = ifelse(cross == 1, self$state[[parents[1]]], self$state[[parents[2L]]])

          # Mutation
          mutation = rbinom(length(self$state[[parents[1]]]), 1, self$settings$mutation_rate)
          children = (children + mutation) %% 2

          # Check max features
          if (is.na(self$settings$max_features) || sum(kid) <= self$settings$max_features) {
            break
          }
        }
        return(children)
      })
    }
  )
)
