# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AV_rcpp <- function(voters, candidates, weights) {
    .Call(`_mlr3fselect_AV_rcpp`, voters, candidates, weights)
}

SAV_rcpp <- function(voters, candidates, weights) {
    .Call(`_mlr3fselect_SAV_rcpp`, voters, candidates, weights)
}

seq_PAV_rcpp <- function(voters, candidates, weights) {
    .Call(`_mlr3fselect_seq_PAV_rcpp`, voters, candidates, weights)
}

revseq_PAV_rcpp <- function(voters, candidates, weights) {
    .Call(`_mlr3fselect_revseq_PAV_rcpp`, voters, candidates, weights)
}

